import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"
import type { ReportStats } from "@/lib/report-stats"

export interface ReportMeta {
  scopeLabel: string // e.g. "Makindye District Office" or "All Districts"
  serviceFilter?: string // e.g. "All services"
  generatedBy: string
}

const NIRA_BLUE: [number, number, number] = [11, 61, 145]
const INK: [number, number, number] = [24, 24, 27]
const MUTED: [number, number, number] = [113, 113, 122]

/** Generate and download a lightweight, branded PDF summary of the scoped report. */
export function exportReportPdf(stats: ReportStats, meta: ReportMeta, filename: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const marginX = 40
  let y = 48

  // Header band
  doc.setFillColor(...NIRA_BLUE)
  doc.rect(0, 0, pageWidth, 84, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.text("NIRA — Outcome Notice Report", marginX, 40)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text("National Identification & Registration Authority", marginX, 58)

  y = 112

  // Meta block
  doc.setTextColor(...INK)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.text("Report summary", marginX, y)
  y += 18

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  const generatedAt = new Date().toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })
  const metaLines = [
    `Scope: ${meta.scopeLabel}`,
    meta.serviceFilter ? `Service filter: ${meta.serviceFilter}` : null,
    `Generated: ${generatedAt}`,
    `Generated by: ${meta.generatedBy}`,
  ].filter(Boolean) as string[]
  for (const line of metaLines) {
    doc.text(line, marginX, y)
    y += 14
  }
  y += 8

  // Key figures table
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Total notices", String(stats.total)],
      ["Resolved", String(stats.resolved)],
      ["Open (awaiting action)", String(stats.open)],
      ["Resolution rate", `${stats.resolutionRate}%`],
      ["SMS delivery rate", `${stats.deliveryRate}%`],
      ["Queued offline", String(stats.queued)],
    ],
    theme: "grid",
    headStyles: { fillColor: NIRA_BLUE, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: marginX, right: marginX },
  })

  // Notices by service
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20,
    head: [["Service", "Notices"]],
    body: stats.byService.map((s) => [s.label, String(s.count)]),
    theme: "striped",
    headStyles: { fillColor: NIRA_BLUE, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: marginX, right: marginX },
  })

  // By case status
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20,
    head: [["Case status", "Notices"]],
    body: stats.byStatus.map((s) => [s.status, String(s.count)]),
    theme: "striped",
    headStyles: { fillColor: NIRA_BLUE, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: marginX, right: marginX },
  })

  // National reports include a district breakdown
  if (stats.byDistrict.length > 1) {
    autoTable(doc, {
      startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20,
      head: [["District office", "Notices"]],
      body: stats.byDistrict.map((d) => [d.district, String(d.count)]),
      theme: "striped",
      headStyles: { fillColor: NIRA_BLUE, textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 10, cellPadding: 6 },
      margin: { left: marginX, right: marginX },
    })
  }

  // Footer note on every page
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const h = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text(
      "Generated by the NIRA Outcome Notice System — figures reflect notices visible to the report scope.",
      marginX,
      h - 24,
    )
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - marginX, h - 24, { align: "right" })
  }

  doc.save(filename)
}
